version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: trend-hunter-db
    environment:
      POSTGRES_USER: trend_hunter
      POSTGRES_PASSWORD: trend_hunter_password
      POSTGRES_DB: trend_hunter
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trend_hunter"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: trend-hunter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:

